log_config:
  formatter_config:
    fmt: '{levelname}: {message}'
    style: '{'
  logging_level: 0
paths:
  log_path: ./logs/log.txt
  metric_path: ./outputs/metrics.yaml
  output_model_path: ./model/model.pkl
  predict_dataset_path: ./data/predict_dataset/predict_dataset.csv
  predict_path: ./outputs/predict.csv
  raw_dataset_path: ./data/raw/healthcare-dataset-stroke-data.csv
  test_dataset_path: ./data/train_test_dataset/test.csv
  train_dataset_path: ./data/train_test_dataset/train.csv
train_config:
  model_type: LR
  column_y: stroke
  random_state: 0
  test_size: 0.3
