apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference-deployment
  labels:
    app: online-inference
spec: 
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference
      labels: 
        app: online-inference
    spec:
      containers:
        - image: nmar33/online_inference:v1
          name: online-inference
          ports:
            - containerPort: 8000