apiVersion: v1
kind: Pod
metadata: 
  name: online-inference-probes-broken
  labels:
    app: online-inference
spec:
  containers:
    - image: nmar33/online_inference:broken
      name: online-inference-image-bag
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      readinessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5



