apiVersion: v1
kind: Pod
metadata: 
  name: online-inference-resources
  labels:
    app: online-inference
spec:
  containers:
    - image: nmar33/online_inference:v1
      name: online-inference-image-1
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

